### ISSUE TITLE
One class it seems to stop taking attendance for a while

### ISSUE THREAD

**Issue by Rossi08** [al-caughey/Google-Meet-Attendance#86]
I am using this extension for all my classes, but one section does not work. I have the same setting for each I assume. It's working in the other 7 classes and I didn't change any. I have attached the attendance. The report even states that I was not present for a while and I was the host. I do not know what is going wrong. Any help would be appreciated.

 ![Attendance problem](https://user-images.githubusercontent.com/72940034/97346747-392c5380-1862-11eb-8cea-f9024521b0e1.jpg)

**Comment by Eagle-Man** [comment]
Hmm...just to check, are you using Grid View (fix) or Google Meet Tiled View?  Also, are you (or anyone else) presenting during this time?  Was there anything else different that you did during this class?

**Comment by Rossi08** [comment]
Thank you for the reply. I am using grid view fix. And I did the exact same things I did in the other classes. I presented from a separate chrome tab. I did nothing different. 

Thanks,

**Comment by Rossi08** [comment]
Do you think it could be something one of my students has/does not have that is affecting the extension?

**Comment by Eagle-Man** [comment]
No.  GMA is only on your own computer and has no access to anything on the student side.  Very strange.  @al-caughey might ask you to send a file or two his way to take a look into this.

**Comment by Eagle-Man** [comment]
No.  This extension is totally self contained on your computer.  It has no access to anything on the student side.

You say you have 7 classes.  How many are in each class, and how many students do you have total?  Also, what OS are you using?  As much information about what you use and how you're using it would be appreciated because there are many who have been experiencing these problems and @al-caughey (and I) have no idea what's causing them.

**Comment by Rossi08** [comment]
How many are in each class, and how many students do you have total?
1a-24 Students
1b-42 Students
4a-47 Students (problem class)
4b-46 Students
7a-32 Students
7b-27 Students
8a-43 Students
8b-45 Students
Also, what OS are you using? Windows 10 Education
As much information about what you use and how you're using it would be appreciated because there are many who have been experiencing these problems and @al-caughey<https://github.com/al-caughey>(and I) have no idea what's causing them.
I open the meet then I choose the appropriate class in the attendance. I now join the meet and open the link for the students.
They answer a question in the Google Classroom.
Once all of the students join, I share a video (from YouTube) for 5 min using a chrome tab.
I stop sharing and we discuss.
I then share my screen that has a document from my google drive through chrome.
Then the students stay on the meet till they answer some questions in the GC as a google form.
I am always the last then I end the meet.
It seems to me that after a few minutes it stops taking attendance. I hit the clock button and it took a few more students as present. I was present the whole time but i was not recorded.
Let me know if you need any more information.

Thank you for your help,

[cid:cd6b61d7-94ed-47b6-9e4f-149426114bb0]​
________________________________

**Comment by Eagle-Man** [comment]
Do you leave the same Meet open for all classes, or do you use different Meets?

At a difference of only one student, I doubt it's a quantity issue.  If you're sharing from the same computer as GMA, it should be fine (though even sharing from a different device would result in more being present than that).

Have you pressed the clock button later in the class for each of your 4a Meets?  That shouldn't really affect the data much more than changing the start time listed in the report, but just checking.

Do any students in the class have any "non-standard" characters in their name?  Accents, hyphens, other punctuation?

Do your students show up as Red in the GMA window during the Meet or are they Green?

Could you perhaps try using the HTML save button to create multiple reports next time?  One right before you share the first time, one in between sharing sessions, and one at the end before everyone signs off?  And also turn on "Generate Log" in settings to help Al get extra info.  If you could do this for 4a and for one other class that works (maybe 4b since it's almost the same size), that could help narrow it down to whether it's a problem all class, or just something at the end.

Sorry it's taking so long to figure out.  It's a tricky one.

**Comment by Rossi08** [comment]
Do you leave the same Meet open for all classes, or do you use different Meets?

-Every class is a different meet. I also reset the codes after every class.


At a difference of only one student, I doubt it's a quantity issue. If you're sharing from the same computer as GMA, it should be fine (though even sharing from a different device would result in more being present than that).

-I sometimes use another devise to share my videos since it works better. I do the same lesson, the same way for all 8 classes.


Have you pressed the clock button later in the class for each of your 4a Meets?

-I have not used the clock in any other class.


Do any students in the class have any "non-standard" characters in their name? Accents, hyphens, other punctuation?

-Yes, a few students have quotation marks "" And i think this is the only class that i have quotation marks. Others classes have apostrophes.


Do your students show up as Red in the GMA window during the Meet or are they Green?

-The students marked on the report are green all others are red.


Could you perhaps try using the HTML save button to create multiple reports next time? One right before you share the first time, one in between sharing sessions, and one at the end before everyone signs off? And also turn on "Generate Log" in settings to help Al get extra info. If you could do this for 4a and for one other class that works (maybe 4b since it's almost the same size), that could help narrow it down to whether it's a problem all class, or just something at the end.

-I will have this class again on Friday, I can do this then.

Once again, thank you for your help.
________________________________

**Comment by Eagle-Man** [comment]
Hmm...it may be the quotation marks.  I wonder if you could try saving a report before that student joins the Meet.
@al-caughey, thoughts on it being quotation marks in the name?

**Comment by Rossi08** [comment]
I had that class today (4A) and it did not work again. I saved the report during class, but it would not let me do it more than the one time. The meet was over at 1:21 but did not record the whole meet. I tried to watch as the students came in and I believe it stopped working once the first student with "" came in (not 100%). I also enabled report for you. I attached the whole file i received for the report.

Please let me know if you need anything else from me.
Thank you for your help.

________________________________

**Comment by Rossi08** [comment]
Is there any way that the attendance extension  can allow quotation marks so that it will work with my class? It seems that might be the reason for the issue. Let me know if you would like more information on my end. 
I know a lot of time  and effort goes into this I appreciate all of it. 

Thanks.

**Comment by Rossi08** [comment]
This is the only class that I have students with nicknames. Like Joseph “Joe” Smith set by our admins for there preferred names. And this is the only class that the extension never worked for. I am assuming that this is an issue for the extension not to work. 

Thanks you for all your work.

**Comment by Eagle-Man** [comment]
Can you copy and paste the name exactly from how it is in Meet/GMA?  Or sent Al a copy of the backup file?  There are a couple different quotation mark characters, so knowing which ones they are would help.

**Comment by Rossi08** [comment]
Here are the names from google classroom
Xian zhuo "Anson" Dong
Yixiao "Yi xiao" Li
Hillary "Anne" Nolasco
Khujista "Umama" Umama

Thanks again for all your work.


________________________________

**Comment by Rossi08** [comment]
Hello,
Just wanted to let you know, if you needed to, that I had the class again and it did not work. 
Also, does it matter if I have the names as they appear in GC with the preferred names or the names without the preferred parentheses for the extension to work?

Thanks for all your work.

**Comment by AlCaughey** [comment]
Just to be clear, when the kids show up on your Google Meet screen, they
appear with the double quotes, right?
When I paste those names into my class list, it blows things up.  I'm
hoping that this does not require changes in *many* spots

**Comment by Eagle-Man** [comment]
The names in the extension must match what shows up in Meet, so if they appear with the preferred name in quotation marks in Meet, that is how they must be in the class list in attendance.

@Al: doesn’t JavaScript have an escape/inescapable function which could be used here?

**Comment by AlCaughey** [comment]
Yup... I've escaped the quotes and it appears to work now... I saw another
bug yesterday so want to fix it too

**Comment by Rossi08** [comment]
Thank you all. I will have that class again on Friday. I will change the names prior to the meet with the exact names in GC. Once again, I thank you both for all the work you put into this one problem.

**Comment by Rossi08** [comment]
Hello,
Sorry to keep emailing you. I am unsure what happened, but the extension did not work for this class again. Some students did register on the attendance extension, but not on the backup file. No one registered. The "" students did not register on the attendance screen. I clicked to report, I hope that okay and I received a yellow box for java script error. I have attached a screen shot. Let me know if I can help in any way.

Thank you,

[cid:acc11f27-f45c-41fc-944d-79c7bb96f884]
[cid:9bba85fb-a84a-42b5-8ad0-d8c57ec2635c]
________________________________

**Comment by Eagle-Man** [comment]
@Rossi08 Hello,
Again, if you reply via email, the images are not attached so we can't see them.  Please sign into GitHub and insert it properly.

**Comment by Rossi08** [comment]
I am unsure what happened, but the extension did not work for this class again. Some students did register on the attendance extension, but not on the backup file. No one registered. The "" students did not register on the attendance screen. I clicked to report, I hope that's okay and I received a yellow box for java script error. I have attached a screen shot. Let me know if I can help in any way and if you need a different image.

Thank you,
![image](https://user-images.githubusercontent.com/72940034/99996458-c4c5d100-2d89-11eb-9a3a-51e75de19aa9.png)

**Comment by Rossi08** [comment]
I had the class today and it did not work. Here is the screen shot I received after class. Let me know if you need anything else.

Thanks again.

![image](https://user-images.githubusercontent.com/72940034/100650685-4c738880-3312-11eb-97a7-9bc2a7ba3e9a.png)

**Comment by Rossi08** [comment]
Hello,
The extension worked while i was on the meet but the report was empty. I have attached a screen shot. Let me know if you need anything else and if you are getting this message. I don't know if I am posting it correctly.

![image](https://user-images.githubusercontent.com/72940034/101203324-7beb0380-3638-11eb-9fb2-908486b0e11c.png)

**Comment by AlCaughey** [comment]
This issue should be fixed now (as of v1.2.7)

**Comment by Rossi08** [comment]
Hello,
I am still having issues with taking attendance for this one class. I took a screen shot of what I received in the file. During class it still stops taking attendance after a little while. Thank you for your help.

![image](https://user-images.githubusercontent.com/72940034/102921034-b4bd1200-4459-11eb-95cc-3c4fb39b3770.png)

**Comment by Rossi08** [comment]
Hello,
During class it took attendance great but I did not get the normal report. It says JavaScript Error. I attached a screenshot. Let me know if you need any more information.

Thank you for all the work you put into this.

![image](https://user-images.githubusercontent.com/72940034/103806392-f1c10100-5022-11eb-8d0b-c337316a2d83.png)

**Comment by Eagle-Man** [comment]
I wonder if those quotation marks are displayed in the console as the standard ASCII quotation marks, but are actually the Unicode slanted quotation marks internally...  @al-caughey / @AlCaughey ?

**Comment by Rossi08** [comment]
Hello,
Here is the screenshot of the errors from the .html report. During the class the extension was taking the attendance automatically, and working great but I received an error report. 

Thank you for all your work. 

![image](https://user-images.githubusercontent.com/72940034/104356235-b1a5c680-54d9-11eb-8f0b-9a39564a90f2.png)

**Comment by Eagle-Man** [comment]
@AlCaughey 
@al-caughey 
Hey Al, any further thoughts on this?  It seems to still be happening in spite of the changes you've made to the regexp.  It looks like it's always happening with that one student, so I'm still wondering if it has to do with the quotation marks in the name.  It's the only thing that looks suspect about it.

**Comment by AlCaughey** [comment]
can you send me the data file please

**Comment by Rossi08** [comment]
Hello,
I am sorry. I am not sure of what you are requesting. If you need something else please let me know what that is and how to access it.

Thank you.

**Comment by Eagle-Man** [comment]
@Rossi08 Al says that the quotation mark issue should be fixed in 1.3.1, released on the weekend, so look for that update to happen (or do it manually) and then try again.

**Comment by Rossi08** [comment]
Thank you. I used it today with that class and it worked flawlessly. I really appreciate all the work you all did and all the time you put into this. 

Thank you again,
